services:
  back-end:
    build:
      context: ./back-end
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/task
    depends_on:
      - db
    volumes:
      - ./back-end:/app

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front-end:
    build:
      context: ./front-end
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - back-end
    volumes:
      - ./front-end:/app

volumes:
  postgres_data:
